Fix sync after recent changes
This commit fixes the following errors introduced in
fb6c709f7d26b4cef0e7b579c7e3da1c029ae103:

UnboundLocalError: local variable 'updated' referenced before assignment

AttributeError: 'Comment' object has no attribute 'file_id'