Fix migration
This is a gertty bug introduced in
https://opendev.org/ttygroup/gertty/commit/73a648183591be81a1a4037b37d8f0f8a8ce1f01

Subsequent migrations calling `sqlite_drop_columns` would fail with:

  sqlalchemy.exc.NoSuchTableError: own_account