Fix db.vacuum
After the bump of sqlalchemy, we're getting an ArgumentError from the
vacuum method:

    sqlalchemy.exc.ArgumentError: Textual SQL expression 'VACUUM' should be explicitly declared as text('VACUUM')