Fix upload review event type
Commit 12c7c27e4aa7dfc20367b5211147867f3c78624f unified the approval
stage with the `getReviewState()` method, however it broke the review
upload to github. Hubtty would report the following error in the logs:

    Exception: Received 422 status code: {"message":"Unprocessable Entity","errors":["Variable $event of type PullRequestReviewEvent was provided invalid value"],"documentation_url":"https://docs.github.com/rest/reference/pulls#create-a-review-for-a-pull-request"}

This new commit ensures the event type is correct per github API.