Import alembic.migration
This is needed for alembic >=1.7, though unfortunately goes entirely
unmentioned in its ChangeLog. Without adding the import, startup
raises this:

    AttributeError: module 'alembic' has no attribute 'migration'

Port commit bff537e87c from opendev.org/ttygroup/gertty